---
title: "DecisionTreeC50"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## identifying risky bank loans using C5.0 decision trees

we use credit.csv data set

### load the library
```{r }
library(C50)       # decision tree algorithm 
library(gmodels)   # for CrossTable
```

### load data set

```{r }
credit <- read.csv("credit.csv")
str(credit)
credit$default <- factor(credit$default, levels = c(1, 2),
                         labels = c("Default", "Not Default"))
```

### Analyze the data
```{r }
table(credit$checking_balance)
table(credit$savings_balance)
summary(credit$months_loan_duration)
summary(credit$amount)
table(credit$default)
```

### Create C5.0 model
```{r }
set.seed(125)
train_sample <- sample(1000, 900)  
str(train_sample)
credit_train <- credit[train_sample, ]
credit_test  <- credit[-train_sample, ]
prop.table(table(credit_train$default))
prop.table(table(credit_test$default))

credit_model <- C5.0(credit_train[-17], credit_train$default, trials=10)
```

### evaluate the model
```{r }
credit_pred <- predict(credit_model, credit_test)

CrossTable(credit_test$default, credit_pred,
             prop.chisq = FALSE, prop.c = FALSE, prop.r = FALSE,
             dnn = c('actual default', 'predicted default'))
```
