---
title: "Linear Regression"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## predicting medical expenses using linear regression

### load the library
```{r }
library(psych)   # for pairs.panels
library(stats)
```

### load the dataset

```{r }
insurance <- read.csv("insurance.csv", stringsAsFactors = TRUE)
str(insurance)
summary(insurance$expenses)
```

### Analyze the dataset
```{r }
hist(insurance$expenses)
table(insurance$region)
cor(insurance[c("age", "bmi", "children", "expenses")])
pairs(insurance[c("age", "bmi", "children", "expenses")])
pairs.panels(insurance[c("age", "bmi", "children", "expenses")])
```

### create the model
```{r }
ins_model <- lm(expenses ~ age + children + bmi + sex +
                    smoker + region, data = insurance)
# ins_model <- lm(expenses ~ ., data = insurance)
```

### improve the model
```{r }
# improving the performance
# adding non linearity 
insurance$age2 <- insurance$age^2

# convert bmi to binary 
insurance$bmi30 <- ifelse(insurance$bmi >= 30, 1, 0)

# adding an interaction between obesity and smoking

ins_model2 <- lm(expenses ~ age + age2 + children + bmi + sex +
                    bmi30*smoker + region, data = insurance)
summary(ins_model2)

```

### evaluate the two models
```{r }
summary(ins_model)

summary(ins_model2)
```