---
title: "Naive Bayes Algorithm"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Filtering mobile phone SMS data with the Naive Bayes algorithm

http://www.dt.fee.unicamp.br/~tiago/smsspamcollection/

```{r }
library(tm)             # R's text Mining library 
library(SnowballC)      # provides stamming function
library(wordcloud)      # for text visualization
library(e1071)          # includes machine learning algorithms like naive bayes
library(gmodels)        # for CrossTable()
```

### load the sms data

```{r }
sms_raw <- read.csv("sms_spam.csv", stringsAsFactors = FALSE)
str(sms_raw)
```


### clean the text data
```{ }
sms_raw$type <- factor(sms_raw$type)
table(sms_raw$type)
sms_corpus <- VCorpus(VectorSource(sms_raw$text))
print(sms_corpus)

inspect(sms_corpus[1:2])   # inspect() creates summary
as.character(sms_corpus[[1]])

lapply(sms_corpus[1:2], as.character)
sms_corpus_clean <- tm_map(sms_corpus, content_transformer(tolower))
as.character(sms_corpus_clean[[1]])

sms_corpus_clean <- tm_map(sms_corpus_clean, removeNumbers)
sms_corpus_clean <- tm_map(sms_corpus_clean, removeWords, stopwords())
sms_corpus_clean <- tm_map(sms_corpus_clean, removePunctuation)

spam <- subset(sms_raw, type == "spam")
ham <- subset(sms_raw, type == "ham")

wordcloud(spam$text, max.words = 40, colors = brewer.pal(5, "Dark2"), scale = c(3, 0.5))
wordcloud(ham$text, max.words = 40, colors = brewer.pal(5, "Dark2"), scale = c(3, 0.5))

sms_corpus_clean <- tm_map(sms_corpus_clean, stemDocument)
sms_corpus_clean <- tm_map(sms_corpus_clean, stripWhitespace)
wordcloud(sms_corpus_clean, min.freq = 50, colors = brewer.pal(5, "Dark2"), random.order = FALSE)

```

# create model
```{r }
sms_dtm <- DocumentTermMatrix(sms_corpus_clean)
sms_dtm_train <- sms_dtm[1:4169, ]                # 75%
sms_dtm_test  <- sms_dtm[4170:5559, ]             # 25%

sms_train_labels <- sms_raw[1:4169, ]$type
sms_test_labels  <- sms_raw[4170:5559, ]$type
prop.table(table(sms_train_labels))
prop.table(table(sms_test_labels))

# eliminate words that appears less than 5 messages
sms_freq_words <- findFreqTerms(sms_dtm_train, 5) 
str(sms_freq_words)
sms_dtm_freq_train<- sms_dtm_train[ , sms_freq_words]  # limits the no of column
sms_dtm_freq_test <- sms_dtm_test[ , sms_freq_words]   # limits the no of column

# create model
convert_counts <- function(x) {
    x <- ifelse(x > 0, "Yes", "No")
}

sms_train <- apply(sms_dtm_freq_train, MARGIN = 2,
                     convert_counts)
sms_test <- apply(sms_dtm_freq_test, MARGIN = 2,
                    convert_counts)
sms_classifier <- naiveBayes(sms_train, sms_train_labels, laplace = 1)
sms_test_pred <- predict(sms_classifier, sms_test)

```

# evaluate the model
```{r }
CrossTable(sms_test_pred, sms_test_labels,
             prop.chisq = FALSE, prop.t = FALSE,
             dnn = c('predicted', 'actual'))
```